### ISSUE TITLE
firefox

### ISSUE THREAD

**Issue by bartzushka** [AyumuKasuga/SocialShare#11]
dont work at firefox 41.0.2

**Comment by AyumuKasuga** [comment]
Do you use some extensions for blocking advertisements (like adblock or ublock)? I tried Firefox 42 with ublock and it blocks load SocialShare.js script. Example started work fine when i switch off ublock extension.

**Comment by bartzushka** [comment]
i use it on Chrome but it was working fine) 
а вообще именно на файрфоксе фейлится)

**Comment by AyumuKasuga** [comment]
Я только что попробовал на версии firefox 41.0.2 с выключенными расширениями, все норм. Мне кажется все же здесь имеет место какое-то расширение которое блокирует загрузку js. А есть в консоли js или в network какие-нибудь ошибоньки?

**Comment by bartzushka** [comment]
http://prntscr.com/93dv47
http://riteshkr.com/socialShare.js/

**Comment by AyumuKasuga** [comment]
А пример в моей репе по ссылке https://raw.githack.com/AyumuKasuga/SocialShare/master/example.html работает? есть каунтеры?

Просто страница http://riteshkr.com/socialShare.js/ не моя и там, как я понял, форкнутый и немного измененный SocialShare.js. И у меня он в Chrome тоже не работает

**Comment by bartzushka** [comment]
о, на файрфоксе поднялся, на твоей репе, но вот у меня не хочет,та же ошикба(

**Comment by AyumuKasuga** [comment]
Потому что в том форке чувак юзает сторонний сервис (http://anyorigin.com), через который он забирает каунтеры для google plus, а он видимо лежит сейчас. У меня в репе https://github.com/AyumuKasuga/SocialShare в данный момент забор google plus лайков работает без дополнительных серверов.

**Comment by bartzushka** [comment]
понял в чем была моя проблема, нужно было вызывать в файле скриптов, а я вызывал в <script>

**Comment by bartzushka** [comment]
а вот счетчик фб перестал работать ((

**Comment by bartzushka** [comment]
и на репе тоже
