### ISSUE TITLE
Facebook counter amount is not equal to what URL linter shows

### ISSUE THREAD

**Issue by mariojankovic** [AyumuKasuga/SocialShare#15]
This is the actual count on the site: http://i.imgur.com/H224d5o.png
And this is what facebook said: http://i.imgur.com/JWHpILu.png

Is this an issue or does it even count in all the comments and stuff? So has the post really been shared only ~700 times?

**Comment by AyumuKasuga** [comment]
Hello! SocialShare counts only shares, without like and comments (`share_count` parameter from facebook api response). On your screenshot I can see sum of likes, shares and comments.

**Comment by mariojankovic** [comment]
Thanks for the clarification! I was afraid this is the case.
