### ISSUE TITLE
I need whatsapp button

### ISSUE THREAD

**Issue by KarloxMartinez** [AyumuKasuga/SocialShare#18]
Ideally you add the button to share on whatsapp

**Comment by KarloxMartinez** [comment]
no response?

**Comment by AyumuKasuga** [comment]
@KarloxMartinez oh sorry, i was on vacationand did not have chance to answer you :(. I googled about whatsapp  share button and i think its possible to add. I'll try to add this today's evening/night (+3GMT)

**Comment by KarloxMartinez** [comment]
Ok, thank you.

**Comment by AyumuKasuga** [comment]
I just added WhatsApp share support. I tried it in chrome on android phone and it's works as expected. Please check it out.

**Comment by KarloxMartinez** [comment]
Thank u. It's perfect.



On Thu, Feb 25, 2016 at 11:08 AM -0800, "Andrey Kostakov" <notifications@github.com<mailto:notifications@github.com>> wrote:


I just added WhatsApp share support. I tried it in chrome on android phone and it's works as expected. Please check it out.

-
