### ISSUE TITLE
Cannot read property 'share_count' of undefined

### ISSUE THREAD

**Issue by val4o0o0** [AyumuKasuga/SocialShare#22]
This appends in my event log, any ideas ?

**Comment by AyumuKasuga** [comment]
Sorry for long answer. Looks like it is wrong json from facebook. Can you provide url which raised this error?

**Comment by val4o0o0** [comment]
No problem. The issue is about http://localhost, on main site have no problem with this error. http://localhost or http://127.0.0.1 gives this error to fb or other providers. Maybe you can set a default values for localhost and 127.0.0.1 - '0', to prevent this errors.

**Comment by AyumuKasuga** [comment]
@val4o0o0 I just added additional validation response from facebook. Thank you for your report :)
