### ISSUE TITLE
Get values from counter

### ISSUE THREAD

**Issue by rrfranco92** [AyumuKasuga/SocialShare#23]
Hey,

Any idea on how can I get the values from two counter so I can do a SUM and display the result?

**Comment by AyumuKasuga** [comment]
Hello!
Yes in latest version you can set optional parameter `increment` to true and then just put multiple classes for container like this:
```javascript
$('.counter').ShareCounter({
    url: 'http://google.com/',
    increment: true
});
```

```html
<span class='counter c_facebook c_plus'></span></p>
```

You can see result in [this example page](https://raw.githack.com/AyumuKasuga/SocialShare/v0.2.15/example.html)
