### ISSUE TITLE
Conflict with VK.Widget

### ISSUE THREAD

**Issue by enjoyiacm** [AyumuKasuga/SocialShare#9]
Hello.

I want to place this [VK widget](https://vk.com/dev/Subscribe) to page with your share script (show VK count — yes). And always get this error message: ``Uncaught TypeError: Cannot read property 'Subscribe' of undefined``.

If delete ``ShareCounter()`` function — widget works fine! What's wrong? How fix it?

Please check this trouble here: https://jsfiddle.net/h580rjbw/

**Comment by enjoyiacm** [comment]
But this share-buttons works fine with VK.Widget — look here: https://github.com/sapegin/social-likes/blob/master/src/social-likes.js#L74-L96

See code example: https://jsfiddle.net/7byha5t3/

**Comment by AyumuKasuga** [comment]
Hello! I think I fixed this, please check it out.

**Comment by enjoyiacm** [comment]
Yep. Thx!
